// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: urlfrontier.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FrontierService_Put_FullMethodName     = "/urlfrontier.FrontierService/Put"
	FrontierService_GetNext_FullMethodName = "/urlfrontier.FrontierService/GetNext"
	FrontierService_Ack_FullMethodName     = "/urlfrontier.FrontierService/Ack"
)

// FrontierServiceClient is the client API for FrontierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FrontierServiceClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	GetNext(ctx context.Context, in *GetNextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UrlItem], error)
	Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error)
}

type frontierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFrontierServiceClient(cc grpc.ClientConnInterface) FrontierServiceClient {
	return &frontierServiceClient{cc}
}

func (c *frontierServiceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, FrontierService_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontierServiceClient) GetNext(ctx context.Context, in *GetNextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UrlItem], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FrontierService_ServiceDesc.Streams[0], FrontierService_GetNext_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetNextRequest, UrlItem]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FrontierService_GetNextClient = grpc.ServerStreamingClient[UrlItem]

func (c *frontierServiceClient) Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, FrontierService_Ack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FrontierServiceServer is the server API for FrontierService service.
// All implementations must embed UnimplementedFrontierServiceServer
// for forward compatibility.
type FrontierServiceServer interface {
	Put(context.Context, *PutRequest) (*PutResponse, error)
	GetNext(*GetNextRequest, grpc.ServerStreamingServer[UrlItem]) error
	Ack(context.Context, *AckRequest) (*AckResponse, error)
	mustEmbedUnimplementedFrontierServiceServer()
}

// UnimplementedFrontierServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFrontierServiceServer struct{}

func (UnimplementedFrontierServiceServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedFrontierServiceServer) GetNext(*GetNextRequest, grpc.ServerStreamingServer[UrlItem]) error {
	return status.Errorf(codes.Unimplemented, "method GetNext not implemented")
}
func (UnimplementedFrontierServiceServer) Ack(context.Context, *AckRequest) (*AckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ack not implemented")
}
func (UnimplementedFrontierServiceServer) mustEmbedUnimplementedFrontierServiceServer() {}
func (UnimplementedFrontierServiceServer) testEmbeddedByValue()                         {}

// UnsafeFrontierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FrontierServiceServer will
// result in compilation errors.
type UnsafeFrontierServiceServer interface {
	mustEmbedUnimplementedFrontierServiceServer()
}

func RegisterFrontierServiceServer(s grpc.ServiceRegistrar, srv FrontierServiceServer) {
	// If the following call pancis, it indicates UnimplementedFrontierServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FrontierService_ServiceDesc, srv)
}

func _FrontierService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontierServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrontierService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontierServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontierService_GetNext_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetNextRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FrontierServiceServer).GetNext(m, &grpc.GenericServerStream[GetNextRequest, UrlItem]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FrontierService_GetNextServer = grpc.ServerStreamingServer[UrlItem]

func _FrontierService_Ack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontierServiceServer).Ack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrontierService_Ack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontierServiceServer).Ack(ctx, req.(*AckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FrontierService_ServiceDesc is the grpc.ServiceDesc for FrontierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FrontierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "urlfrontier.FrontierService",
	HandlerType: (*FrontierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _FrontierService_Put_Handler,
		},
		{
			MethodName: "Ack",
			Handler:    _FrontierService_Ack_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetNext",
			Handler:       _FrontierService_GetNext_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "urlfrontier.proto",
}
