// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: urlfrontier.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UrlItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Priority      int64                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlItem) Reset() {
	*x = UrlItem{}
	mi := &file_urlfrontier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlItem) ProtoMessage() {}

func (x *UrlItem) ProtoReflect() protoreflect.Message {
	mi := &file_urlfrontier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlItem.ProtoReflect.Descriptor instead.
func (*UrlItem) Descriptor() ([]byte, []int) {
	return file_urlfrontier_proto_rawDescGZIP(), []int{0}
}

func (x *UrlItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UrlItem) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *UrlItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UrlItem) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UrlItem             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_urlfrontier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlfrontier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_urlfrontier_proto_rawDescGZIP(), []int{1}
}

func (x *PutRequest) GetItems() []*UrlItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_urlfrontier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urlfrontier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_urlfrontier_proto_rawDescGZIP(), []int{2}
}

func (x *PutResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

type GetNextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextRequest) Reset() {
	*x = GetNextRequest{}
	mi := &file_urlfrontier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextRequest) ProtoMessage() {}

func (x *GetNextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlfrontier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextRequest.ProtoReflect.Descriptor instead.
func (*GetNextRequest) Descriptor() ([]byte, []int) {
	return file_urlfrontier_proto_rawDescGZIP(), []int{3}
}

func (x *GetNextRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetNextRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_urlfrontier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlfrontier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_urlfrontier_proto_rawDescGZIP(), []int{4}
}

func (x *AckRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acked         int32                  `protobuf:"varint,1,opt,name=acked,proto3" json:"acked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_urlfrontier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urlfrontier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_urlfrontier_proto_rawDescGZIP(), []int{5}
}

func (x *AckResponse) GetAcked() int32 {
	if x != nil {
		return x.Acked
	}
	return 0
}

var File_urlfrontier_proto protoreflect.FileDescriptor

const file_urlfrontier_proto_rawDesc = "" +
	"\n" +
	"\x11urlfrontier.proto\x12\vurlfrontier\"]\n" +
	"\aUrlItem\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x03R\bpriority\"8\n" +
	"\n" +
	"PutRequest\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.urlfrontier.UrlItemR\x05items\")\n" +
	"\vPutResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\"<\n" +
	"\x0eGetNextRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x1e\n" +
	"\n" +
	"AckRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"#\n" +
	"\vAckResponse\x12\x14\n" +
	"\x05acked\x18\x01 \x01(\x05R\x05acked2\xc5\x01\n" +
	"\x0fFrontierService\x128\n" +
	"\x03Put\x12\x17.urlfrontier.PutRequest\x1a\x18.urlfrontier.PutResponse\x12>\n" +
	"\aGetNext\x12\x1b.urlfrontier.GetNextRequest\x1a\x14.urlfrontier.UrlItem0\x01\x128\n" +
	"\x03Ack\x12\x17.urlfrontier.AckRequest\x1a\x18.urlfrontier.AckResponseB\x1dZ\x1bowlite/frontier/proto;protob\x06proto3"

var (
	file_urlfrontier_proto_rawDescOnce sync.Once
	file_urlfrontier_proto_rawDescData []byte
)

func file_urlfrontier_proto_rawDescGZIP() []byte {
	file_urlfrontier_proto_rawDescOnce.Do(func() {
		file_urlfrontier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_urlfrontier_proto_rawDesc), len(file_urlfrontier_proto_rawDesc)))
	})
	return file_urlfrontier_proto_rawDescData
}

var file_urlfrontier_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_urlfrontier_proto_goTypes = []any{
	(*UrlItem)(nil),        // 0: urlfrontier.UrlItem
	(*PutRequest)(nil),     // 1: urlfrontier.PutRequest
	(*PutResponse)(nil),    // 2: urlfrontier.PutResponse
	(*GetNextRequest)(nil), // 3: urlfrontier.GetNextRequest
	(*AckRequest)(nil),     // 4: urlfrontier.AckRequest
	(*AckResponse)(nil),    // 5: urlfrontier.AckResponse
}
var file_urlfrontier_proto_depIdxs = []int32{
	0, // 0: urlfrontier.PutRequest.items:type_name -> urlfrontier.UrlItem
	1, // 1: urlfrontier.FrontierService.Put:input_type -> urlfrontier.PutRequest
	3, // 2: urlfrontier.FrontierService.GetNext:input_type -> urlfrontier.GetNextRequest
	4, // 3: urlfrontier.FrontierService.Ack:input_type -> urlfrontier.AckRequest
	2, // 4: urlfrontier.FrontierService.Put:output_type -> urlfrontier.PutResponse
	0, // 5: urlfrontier.FrontierService.GetNext:output_type -> urlfrontier.UrlItem
	5, // 6: urlfrontier.FrontierService.Ack:output_type -> urlfrontier.AckResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_urlfrontier_proto_init() }
func file_urlfrontier_proto_init() {
	if File_urlfrontier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_urlfrontier_proto_rawDesc), len(file_urlfrontier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_urlfrontier_proto_goTypes,
		DependencyIndexes: file_urlfrontier_proto_depIdxs,
		MessageInfos:      file_urlfrontier_proto_msgTypes,
	}.Build()
	File_urlfrontier_proto = out.File
	file_urlfrontier_proto_goTypes = nil
	file_urlfrontier_proto_depIdxs = nil
}
